import { registerCards } from '@/core/registries/CardRegistry';
import type { CardDefinition } from '@/entities';

const CARDS: CardDefinition[] = [
  {
    id: 'strike',
    name: '贯击',
    type: 'attack',
    rarity: 'basic',
    cost: 1,
    description: '造成 6 点伤害。',
    effects: { damage: 6 },
    image: 'assets/cards/strike.svg',
    upgrade: { description: '造成 9 点伤害。', effects: { damage: 9 } },
    _design: { archetype: '基础输出', balance: '1 费基础攻击标尺，升级后接近普通攻击上限。' },
  },
  {
    id: 'defend',
    name: '固壁',
    type: 'skill',
    rarity: 'basic',
    cost: 1,
    description: '获得 5 点格挡。',
    effects: { block: 5 },
    image: 'assets/cards/defend.svg',
    upgrade: { description: '获得 8 点格挡。', effects: { block: 8 } },
    _design: { archetype: '基础防御', balance: '低于专职防御牌，保持起始牌需要替换的空间。' },
  },

  {
    id: 'expose_core',
    name: '破核标记',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    description: '给予 2 层易伤。抽 1 张牌。',
    effects: { draw: 1, applyStatus: { id: 'vulnerable', stacks: 2, target: 'enemy' } },
    image: 'assets/cards/conduit_strike.svg',
    upgrade: { description: '给予 3 层易伤。抽 1 张牌。', effects: { applyStatus: { id: 'vulnerable', stacks: 3, target: 'enemy' } } },
    _design: { archetype: '通用标记', balance: '不直接造成伤害，作为后续攻击的铺垫。' },
  },
  {
    id: 'guard_break',
    name: '破盾打击',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    description: '造成 5 点伤害。给予 1 层易伤。',
    effects: { damage: 5, applyStatus: { id: 'vulnerable', stacks: 1, target: 'enemy' } },
    image: 'assets/cards/strike.svg',
    upgrade: { description: '造成 7 点伤害。给予 1 层易伤。', effects: { damage: 7 } },
    _design: { archetype: '通用压制', balance: '伤害低于贯击，用易伤补足长期收益。' },
  },
  {
    id: 'momentum',
    name: '整流步',
    type: 'skill',
    rarity: 'common',
    cost: 0,
    description: '获得 1 点能量。消耗。',
    effects: { energy: 1 },
    exhaust: true,
    image: 'assets/cards/overcharge.svg',
    upgrade: { description: '获得 1 点能量。抽 1 张牌。消耗。', effects: { draw: 1 } },
    _design: { archetype: '通用节奏', balance: '一次性加速，不长期扩大资源。' },
  },
  {
    id: 'quick_repair',
    name: '快速修补',
    type: 'skill',
    rarity: 'common',
    cost: 0,
    description: '获得 3 点格挡。抽 1 张牌。消耗。',
    effects: { block: 3, draw: 1 },
    exhaust: true,
    image: 'assets/cards/defend.svg',
    upgrade: { description: '获得 5 点格挡。抽 1 张牌。消耗。', effects: { block: 5 } },
    _design: { archetype: '通用循环', balance: '零费但消耗，适合润滑回合而不是堆防核心。' },
  },
  {
    id: 'steady_ward',
    name: '稳态护符',
    type: 'power',
    rarity: 'uncommon',
    cost: 1,
    description: '获得 1 点敏捷。消耗。',
    effects: { applyStatus: { id: 'dexterity', stacks: 1, target: 'self' } },
    exhaust: true,
    image: 'assets/cards/battery_shield.svg',
    upgrade: { description: '获得 2 点敏捷。消耗。', effects: { applyStatus: { id: 'dexterity', stacks: 2, target: 'self' } } },
    _design: { archetype: '通用成长', balance: '稳定强化防御，但需要一回合投入。' },
  },

  {
    id: 'spark_dash',
    name: '火花突袭',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    description: '造成 5 点伤害。抽 1 张牌。',
    effects: { damage: 5, draw: 1 },
    characterId: 'fluxbreaker',
    image: 'assets/cards/spark_dash.svg',
    upgrade: { description: '造成 7 点伤害。抽 1 张牌。', effects: { damage: 7 } },
    _design: { archetype: '破流者循环攻击', balance: '过牌降低基础伤害，适合作为连锁入口。' },
  },
  {
    id: 'battery_shield',
    name: '电池护盾',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    description: '获得 5 点格挡。抽 1 张牌。',
    effects: { block: 5, draw: 1 },
    characterId: 'fluxbreaker',
    image: 'assets/cards/battery_shield.svg',
    upgrade: { description: '获得 7 点格挡。抽 1 张牌。', effects: { block: 7 } },
    _design: { archetype: '破流者循环防御', balance: '与火花突袭形成攻防过牌对。' },
  },
  {
    id: 'conduit_strike',
    name: '导流斩',
    type: 'attack',
    rarity: 'common',
    cost: 0,
    description: '造成 3 点伤害。',
    effects: { damage: 3 },
    characterId: 'fluxbreaker',
    image: 'assets/cards/conduit_strike.svg',
    upgrade: { description: '造成 4 点伤害。抽 1 张牌。', effects: { damage: 4, draw: 1 } },
    _design: { archetype: '零费触发', balance: '未升级不返牌，避免免费无限循环。' },
  },
  {
    id: 'arc_loop',
    name: '弧光回路',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    description: '获得 4 点格挡。获得 1 点能量。',
    effects: { block: 4, energy: 1 },
    characterId: 'fluxbreaker',
    image: 'assets/cards/battery_shield.svg',
    upgrade: { description: '获得 6 点格挡。获得 1 点能量。', effects: { block: 6 } },
    _design: { archetype: '能量转换', balance: '净费用为 0，但需要先有 1 点能量启动。' },
  },
  {
    id: 'overcharge',
    name: '超载',
    type: 'skill',
    rarity: 'uncommon',
    cost: 1,
    description: '获得 2 点能量。抽 1 张牌。消耗。',
    effects: { energy: 2, draw: 1 },
    exhaust: true,
    characterId: 'fluxbreaker',
    image: 'assets/cards/overcharge.svg',
    upgrade: { description: '获得 2 点能量。抽 2 张牌。消耗。', effects: { draw: 2 } },
    _design: { archetype: '爆发启动', balance: '净 +1 能量且消耗，支撑爆发但不可反复刷。' },
  },
  {
    id: 'voltage_barrage',
    name: '电压齐射',
    type: 'attack',
    rarity: 'uncommon',
    cost: 2,
    description: '造成 4 点伤害，攻击 3 次。',
    effects: { damage: 4, hits: 3 },
    characterId: 'fluxbreaker',
    image: 'assets/cards/spark_dash.svg',
    upgrade: { description: '造成 5 点伤害，攻击 3 次。', effects: { damage: 5 } },
    _design: { archetype: '多段攻击', balance: '吃力量收益更高，因此基础伤害控制在 12。' },
  },
  {
    id: 'power_surge',
    name: '功率激增',
    type: 'power',
    rarity: 'uncommon',
    cost: 1,
    description: '获得 2 点力量。消耗。',
    effects: { applyStatus: { id: 'strength', stacks: 2, target: 'self' } },
    exhaust: true,
    characterId: 'fluxbreaker',
    image: 'assets/cards/overcharge.svg',
    upgrade: { description: '获得 3 点力量。消耗。', effects: { applyStatus: { id: 'strength', stacks: 3, target: 'self' } } },
    _design: { archetype: '攻击成长', balance: '强化多段攻击，但需要牺牲当前回合节奏。' },
  },
  {
    id: 'static_guard',
    name: '静电立场',
    type: 'skill',
    rarity: 'rare',
    cost: 2,
    description: '获得 10 点格挡。获得 1 点敏捷。',
    effects: { block: 10, applyStatus: { id: 'dexterity', stacks: 1, target: 'self' } },
    characterId: 'fluxbreaker',
    image: 'assets/cards/battery_shield.svg',
    upgrade: { description: '获得 13 点格挡。获得 1 点敏捷。', effects: { block: 13 } },
    _design: { archetype: '防御成长', balance: '稀有牌给成长，但 2 费避免过早无脑叠防。' },
  },

  {
    id: 'frost_bolt',
    name: '霜矢',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    description: '造成 5 点伤害。给予 1 层虚弱。',
    effects: { damage: 5, applyStatus: { id: 'weak', stacks: 1, target: 'enemy' } },
    characterId: 'frostseeker',
    image: 'assets/cards/frost_bolt.svg',
    upgrade: { description: '造成 7 点伤害。给予 2 层虚弱。', effects: { damage: 7, applyStatus: { id: 'weak', stacks: 2, target: 'enemy' } } },
    _design: { archetype: '霜寻者控攻', balance: '伤害偏低，用虚弱换取生存。' },
  },
  {
    id: 'ice_barrier',
    name: '冰壁',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    description: '获得 7 点格挡。',
    effects: { block: 7 },
    characterId: 'frostseeker',
    image: 'assets/cards/ice_barrier.svg',
    upgrade: { description: '获得 10 点格挡。', effects: { block: 10 } },
    _design: { archetype: '霜寻者基础防御', balance: '高于固壁，补偿霜寻者输出偏低。' },
  },
  {
    id: 'chill_mine',
    name: '凝霜陷阱',
    type: 'skill',
    rarity: 'uncommon',
    cost: 1,
    description: '获得 4 点格挡。给予 2 层虚弱。抽 1 张牌。',
    effects: { block: 4, draw: 1, applyStatus: { id: 'weak', stacks: 2, target: 'enemy' } },
    characterId: 'frostseeker',
    image: 'assets/cards/chill_mine.svg',
    upgrade: { description: '获得 6 点格挡。给予 2 层虚弱。抽 1 张牌。', effects: { block: 6 } },
    _design: { archetype: '控场循环', balance: '三效果合一但每项数值都压低。' },
  },
  {
    id: 'snowblind',
    name: '雪盲术',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    description: '给予所有敌人 1 层虚弱。抽 1 张牌。',
    effects: { draw: 1, applyStatus: { id: 'weak', stacks: 1, target: 'all_enemies' } },
    characterId: 'frostseeker',
    image: 'assets/cards/chill_mine.svg',
    upgrade: { description: '给予所有敌人 2 层虚弱。抽 1 张牌。', effects: { applyStatus: { id: 'weak', stacks: 2, target: 'all_enemies' } } },
    _design: { archetype: '群体控场', balance: '无伤害，主要处理多敌人场景。' },
  },
  {
    id: 'crystallize',
    name: '晶化护甲',
    type: 'skill',
    rarity: 'uncommon',
    cost: 2,
    description: '获得 14 点格挡。抽 1 张牌。',
    effects: { block: 14, draw: 1 },
    characterId: 'frostseeker',
    image: 'assets/cards/ice_barrier.svg',
    upgrade: { description: '获得 18 点格挡。抽 1 张牌。', effects: { block: 18 } },
    _design: { archetype: '高费防御', balance: '2 费大防御，给控制流抵抗爆发。' },
  },
  {
    id: 'glacial_focus',
    name: '凝冰心法',
    type: 'power',
    rarity: 'rare',
    cost: 1,
    description: '每回合开始时获得 3 点格挡。消耗。',
    effects: { custom: 'gain_block_each_turn_3' },
    exhaust: true,
    characterId: 'frostseeker',
    image: 'assets/cards/glacial_focus.svg',
    upgrade: { description: '每回合开始时获得 4 点格挡。消耗。', effects: { custom: 'gain_block_each_turn_4' } },
    _design: { archetype: '长期防御', balance: '慢收益，适合持久战，不提供即时高额格挡。' },
  },
  {
    id: 'frost_lance',
    name: '冰棱枪',
    type: 'attack',
    rarity: 'uncommon',
    cost: 2,
    description: '造成 12 点伤害。给予 2 层易伤。',
    effects: { damage: 12, applyStatus: { id: 'vulnerable', stacks: 2, target: 'enemy' } },
    characterId: 'frostseeker',
    image: 'assets/cards/frost_bolt.svg',
    upgrade: { description: '造成 16 点伤害。给予 2 层易伤。', effects: { damage: 16 } },
    _design: { archetype: '霜寻者终结牌', balance: '2 费中伤害加易伤，主要服务下一张攻击。' },
  },
];

registerCards(CARDS);
