import { registerCards } from '@/core/registries/CardRegistry';
import type { CardDefinition } from '@/entities';

const MINIMAL_CARDS: CardDefinition[] = [
  {
    id: 'strike',
    name: '贯击',
    type: 'attack',
    rarity: 'basic',
    cost: 1,
    description: '造成 6 点伤害。',
    effects: { damage: 6 },
    image: 'assets/cards/strike.svg',
    upgrade: { description: '造成 9 点伤害。', effects: { damage: 9 } },
  },
  {
    id: 'defend',
    name: '固壁',
    type: 'skill',
    rarity: 'basic',
    cost: 1,
    description: '获得 5 点格挡。',
    effects: { block: 5 },
    image: 'assets/cards/defend.svg',
    upgrade: { description: '获得 8 点格挡。', effects: { block: 8 } },
  },
  {
    id: 'spark_dash',
    name: '火花突袭',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    description: '造成 6 点伤害。抽 1 张牌。',
    effects: { damage: 6, draw: 1 },
    characterId: 'fluxbreaker',
    image: 'assets/cards/spark_dash.svg',
    upgrade: { description: '造成 8 点伤害。抽 1 张牌。', effects: { damage: 8 } },
  },
  {
    id: 'battery_shield',
    name: '电池护盾',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    description: '获得 5 点格挡。抽 1 张牌。',
    effects: { block: 5, draw: 1 },
    characterId: 'fluxbreaker',
    image: 'assets/cards/battery_shield.svg',
    upgrade: { description: '获得 7 点格挡。抽 1 张牌。', effects: { block: 7 } },
  },
  {
    id: 'overcharge',
    name: '超载',
    type: 'skill',
    rarity: 'uncommon',
    cost: 1,
    description: '获得 2 点能量。抽 1 张牌。消耗。',
    effects: { energy: 2, draw: 1 },
    exhaust: true,
    characterId: 'fluxbreaker',
    image: 'assets/cards/overcharge.svg',
    upgrade: { description: '获得 2 点能量。抽 2 张牌。消耗。', effects: { draw: 2 } },
  },
  {
    id: 'conduit_strike',
    name: '导流斩',
    type: 'attack',
    rarity: 'common',
    cost: 0,
    description: '造成 3 点伤害。抽 1 张牌。',
    effects: { damage: 3, draw: 1 },
    characterId: 'fluxbreaker',
    image: 'assets/cards/conduit_strike.svg',
    upgrade: { description: '造成 5 点伤害。抽 1 张牌。', effects: { damage: 5 } },
  },
  {
    id: 'power_surge',
    name: '功率激增',
    type: 'power',
    rarity: 'uncommon',
    cost: 1,
    description: '获得 2 点力量。',
    effects: { applyStatus: { id: 'strength', stacks: 2, target: 'self' } },
    exhaust: true,
    characterId: 'fluxbreaker',
    image: 'assets/cards/overcharge.svg',
    upgrade: { description: '获得 3 点力量。', effects: { applyStatus: { id: 'strength', stacks: 3, target: 'self' } } },
  },
  {
    id: 'static_guard',
    name: '静电立场',
    type: 'skill',
    rarity: 'rare',
    cost: 1,
    description: '获得 8 点格挡。获得 1 点敏捷。',
    effects: { block: 8, applyStatus: { id: 'dexterity', stacks: 1, target: 'self' } },
    characterId: 'fluxbreaker',
    image: 'assets/cards/battery_shield.svg',
    upgrade: { description: '获得 11 点格挡。获得 1 点敏捷。', effects: { block: 11 } },
  },
  {
    id: 'frost_bolt',
    name: '霜矢',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    description: '造成 5 点伤害。给予 1 层虚弱。',
    effects: { damage: 5, applyStatus: { id: 'weak', stacks: 1, target: 'enemy' } },
    characterId: 'frostseeker',
    image: 'assets/cards/frost_bolt.svg',
    upgrade: { description: '造成 7 点伤害。给予 2 层虚弱。', effects: { damage: 7, applyStatus: { id: 'weak', stacks: 2, target: 'enemy' } } },
  },
  {
    id: 'ice_barrier',
    name: '冰壁',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    description: '获得 7 点格挡。',
    effects: { block: 7 },
    characterId: 'frostseeker',
    image: 'assets/cards/ice_barrier.svg',
    upgrade: { description: '获得 10 点格挡。', effects: { block: 10 } },
  },
  {
    id: 'chill_mine',
    name: '凝霜陷阱',
    type: 'skill',
    rarity: 'uncommon',
    cost: 1,
    description: '获得 4 点格挡。给予 2 层虚弱。抽 1 张牌。',
    effects: { block: 4, draw: 1, applyStatus: { id: 'weak', stacks: 2, target: 'enemy' } },
    characterId: 'frostseeker',
    image: 'assets/cards/chill_mine.svg',
    upgrade: { description: '获得 6 点格挡。给予 3 层虚弱。抽 1 张牌。', effects: { block: 6, applyStatus: { id: 'weak', stacks: 3, target: 'enemy' } } },
  },
  {
    id: 'glacial_focus',
    name: '凝冰心法',
    type: 'power',
    rarity: 'rare',
    cost: 1,
    description: '每回合开始时获得 3 点格挡。',
    effects: { custom: 'gain_block_each_turn_3' },
    exhaust: true,
    characterId: 'frostseeker',
    image: 'assets/cards/glacial_focus.svg',
    upgrade: { description: '每回合开始时获得 4 点格挡。', effects: { custom: 'gain_block_each_turn_4' } },
  },
  {
    id: 'expose_core',
    name: '破核标记',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    description: '给予 2 层易伤。抽 1 张牌。',
    effects: { draw: 1, applyStatus: { id: 'vulnerable', stacks: 2, target: 'enemy' } },
    image: 'assets/cards/conduit_strike.svg',
    upgrade: { description: '给予 3 层易伤。抽 1 张牌。', effects: { applyStatus: { id: 'vulnerable', stacks: 3, target: 'enemy' } } },
  },
  {
    id: 'frost_lance',
    name: '冰棱枪',
    type: 'attack',
    rarity: 'uncommon',
    cost: 2,
    description: '造成 13 点伤害。给予 2 层易伤。',
    effects: { damage: 13, applyStatus: { id: 'vulnerable', stacks: 2, target: 'enemy' } },
    characterId: 'frostseeker',
    image: 'assets/cards/frost_bolt.svg',
    upgrade: { description: '造成 17 点伤害。给予 2 层易伤。', effects: { damage: 17 } },
  },
];

registerCards(MINIMAL_CARDS);
