/** 卡牌内容目录 — 本最小版本包含约 10 张卡牌 */
/**
 * 每张卡牌可通过 `image` 和 `imageUpgraded` 指定资源路径，
 * 路径相对 `public/`，例如 `assets/cards/your_card.png`。
 */
import { registerCards } from '@/core/registries/CardRegistry';
import type { CardDefinition } from '@/entities';

const MINIMAL_CARDS: CardDefinition[] = [
  {
    id: 'strike',
    name: '贯击',
    type: 'attack',
    rarity: 'basic',
    cost: 1,
    description: '造成 7 点伤害。',
    effects: { damage: 7 },
    image: 'assets/cards/strike.svg',
    upgrade: { description: '造成 10 点伤害。', effects: { damage: 10 } },
    _design: {
      purpose: '基础攻击牌，作为所有角色的通用输出',
      archetype: '直伤',
      risks: '数值太高会让基础输出过于强势',
      balance: '保持与防御的基础效率平衡',
    },
  },
  {
    id: 'defend',
    name: '固壁',
    type: 'skill',
    rarity: 'basic',
    cost: 1,
    description: '获得 6 点格挡。',
    effects: { block: 6 },
    image: 'assets/cards/defend.svg',
    upgrade: { description: '获得 9 点格挡。', effects: { block: 9 } },
    _design: {
      purpose: '基础防御牌，保证角色早期生存',
      archetype: '格挡',
      risks: '太强会降低转型卡牌的价值',
      balance: '让前几层坦度稳定，同时保持卡池成长需求',
    },
  },
  {
    id: 'spark_dash',
    name: '火花突袭',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    description: '造成 8 点伤害。抽 1 张牌。',
    effects: { damage: 8, draw: 1 },
    characterId: 'fluxbreaker',
    image: 'assets/cards/spark_dash.svg',
    upgrade: { description: '造成 11 点伤害。抽 1 张牌。', effects: { damage: 11 } },
    _design: {
      purpose: '提升能量利用率并帮助快速循环卡组',
      archetype: '过牌',
      risks: '与低抽牌手牌池耦合较深',
      balance: '适当降低伤害，保证优秀过牌收益',
    },
  },
  {
    id: 'battery_shield',
    name: '电池护盾',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    description: '获得 6 点格挡。抽 1 张牌。',
    effects: { block: 6, draw: 1 },
    characterId: 'fluxbreaker',
    image: 'assets/cards/battery_shield.svg',
    upgrade: { description: '获得 9 点格挡。抽 1 张牌。', effects: { block: 9 } },
    _design: {
      purpose: '提供防御与循环，降低手牌堵塞概率',
      archetype: '防守',
      risks: '如果卡池过多防御牌，可能降低攻击节奏',
      balance: '防御值和抽牌效果要与基础防御卡区分',
    },
  },
  {
    id: 'overcharge',
    name: '超载',
    type: 'skill',
    rarity: 'uncommon',
    cost: 2,
    description: '获得 1 点额外能量。抽 1 张牌。',
    effects: { energy: 1, draw: 1 },
    characterId: 'fluxbreaker',
    image: 'assets/cards/overcharge.svg',
    upgrade: { description: '获得 1 点额外能量。抽 2 张牌。', effects: { energy: 1, draw: 2 } },
    _design: {
      purpose: '强化节奏型角色的能量循环能力',
      archetype: '能量增幅',
      risks: '能量过高会弱化其他循环卡的必要性',
      balance: '高费用但提供稳定回能，需保持付出与回报对等',
    },
  },
  {
    id: 'conduit_strike',
    name: '导流斩',
    type: 'attack',
    rarity: 'common',
    cost: 0,
    description: '造成 4 点伤害。抽 1 张牌。',
    effects: { damage: 4, draw: 1 },
    characterId: 'fluxbreaker',
    image: 'assets/cards/conduit_strike.svg',
    upgrade: { description: '造成 6 点伤害。抽 1 张牌。', effects: { damage: 6 } },
    _design: {
      purpose: '让零耗攻击牌成为连击与资源循环的基础',
      archetype: '零耗',
      risks: '若数值过高会削弱其他 0 费牌的角色定位',
      balance: '保持低伤害但高循环价值',
    },
  },
  {
    id: 'frost_bolt',
    name: '霜矢',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    description: '造成 6 点伤害。',
    effects: { damage: 6 },
    characterId: 'frostseeker',
    image: 'assets/cards/frost_bolt.svg',
    upgrade: { description: '造成 9 点伤害。', effects: { damage: 9 } },
    _design: {
      purpose: '提供稳定单体伤害，与控制机制搭配',
      archetype: '冰霜输出',
      risks: '偏向基础打击，需结合防御卡保持整体强度',
      balance: '让冷系角色有可靠基础输出来源',
    },
  },
  {
    id: 'ice_barrier',
    name: '冰壁',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    description: '获得 7 点格挡。',
    effects: { block: 7 },
    characterId: 'frostseeker',
    image: 'assets/cards/ice_barrier.svg',
    upgrade: { description: '获得 10 点格挡。', effects: { block: 10 } },
    _design: {
      purpose: '基础防御卡，为冰系角色提供稳定承受',
      archetype: '格挡',
      risks: '高效格挡会降低对特殊防御卡的需求',
      balance: '保持与其他角色基础防御卡类似的防御效率',
    },
  },
  {
    id: 'chill_mine',
    name: '凝霜陷阱',
    type: 'skill',
    rarity: 'uncommon',
    cost: 1,
    description: '获得 4 点格挡。抽 1 张牌。',
    effects: { block: 4, draw: 1 },
    characterId: 'frostseeker',
    image: 'assets/cards/chill_mine.svg',
    upgrade: { description: '获得 6 点格挡。抽 1 张牌。', effects: { block: 6 } },
    _design: {
      purpose: '减缓敌方节奏并提高卡组流畅度',
      archetype: '防守循环',
      risks: '与其他低耗防御卡重合时价值下降',
      balance: '要保持比基础防御更高的循环价值',
    },
  },
  {
    id: 'glacial_focus',
    name: '凝冰心法',
    type: 'power',
    rarity: 'rare',
    cost: 2,
    description: '回合开始时获得 2 点格挡。',
    effects: { custom: 'gain_block_each_turn_2' },
    characterId: 'frostseeker',
    image: 'assets/cards/glacial_focus.svg',
    upgrade: { description: '回合开始时获得 3 点格挡。', effects: { custom: 'gain_block_each_turn_3' } },
    _design: {
      purpose: '提供持续资源，让控制流在近战中更稳健',
      archetype: '持续防御',
      risks: '若触发机制未完善，可能无法体现价值',
      balance: '保持稳定但不能完全替代即时格挡',
    },
  },
];

registerCards(MINIMAL_CARDS);
