import { registerCharacter } from '@/core/registries/CharacterRegistry';
import type { CharacterDefinition } from '@/entities';

const FLUX_DECK = [
  'strike',
  'strike',
  'defend',
  'defend',
  'spark_dash',
  'battery_shield',
  'conduit_strike',
  'arc_loop',
];

const FROST_DECK = [
  'strike',
  'strike',
  'defend',
  'defend',
  'frost_bolt',
  'ice_barrier',
  'chill_mine',
  'snowblind',
];

const CONTROL_DECK = [
  'strike',
  'defend',
  'defend',
  'expose_core',
  'guard_break',
  'battery_shield',
  'quick_repair',
  'ice_barrier',
];

const BURST_DECK = [
  'strike',
  'strike',
  'spark_dash',
  'conduit_strike',
  'guard_break',
  'defend',
  'defend',
  'momentum',
];

export const CHARACTERS: CharacterDefinition[] = [
  {
    id: 'fluxbreaker',
    name: '破流者',
    title: '断流者',
    maxHp: 72,
    startingGold: 80,
    startingDeck: FLUX_DECK,
    startingRelics: ['flux_core'],
    description: '擅长将能量凝聚成快速打击，擅长在战斗中借势反击。',
    color: '#d97632',
    portrait: 'assets/characters/fluxbreaker.png',
    _design: {
      purpose: '提供节奏型输出与能量循环体验',
      archetypes: ['能量循环', '连击', '快攻'],
      risks: '过度依赖能量收益时，低费手牌可能被快速打空',
      balance: '起手稳定，适合作为默认角色',
    },
  },
  {
    id: 'frostseeker',
    name: '霜寻者',
    title: '寒冰贤者',
    maxHp: 68,
    startingGold: 90,
    startingDeck: FROST_DECK,
    startingRelics: ['glacial_globe'],
    description: '借助寒冰构筑战场节奏，以控制和循环资源压制对手。',
    color: '#3c81c9',
    portrait: 'assets/characters/frostseeker.png',
    _design: {
      purpose: '构建慢热控制流，利用防御与虚弱效果拖长战斗',
      archetypes: ['控制', '过牌', '防御'],
      risks: '早期输出略低，需要合理规划回合节奏',
      balance: '更稳定但爆发较弱',
    },
  },
  {
    id: 'void_scribe',
    name: '虚空书记',
    title: '裂隙记录者',
    maxHp: 66,
    startingGold: 95,
    startingDeck: CONTROL_DECK,
    startingRelics: ['spark_capacitor'],
    description: '记录敌人的破绽，通过标记、抽牌和技能连锁逐步扩大优势。',
    color: '#9b6dff',
    _design: { archetypes: ['标记', '技能链', '资源'] },
  },
  {
    id: 'ember_knight',
    name: '烬火骑士',
    title: '余烬先锋',
    maxHp: 76,
    startingGold: 70,
    startingDeck: BURST_DECK,
    startingRelics: ['flux_core'],
    description: '偏向正面压制的近战英雄，用高爆发攻击快速结束战斗。',
    color: '#ff6b3d',
    _design: { archetypes: ['爆发', '攻击', '高风险'] },
  },
  {
    id: 'mirror_monk',
    name: '镜相武僧',
    title: '回声行者',
    maxHp: 70,
    startingGold: 85,
    startingDeck: FLUX_DECK,
    startingRelics: ['spark_capacitor'],
    description: '通过低费牌和技能触发不断制造回合内节奏，适合连锁构筑。',
    color: '#58d6b4',
    _design: { archetypes: ['低费', '连锁', '节奏'] },
  },
  {
    id: 'iron_oracle',
    name: '铁幕先知',
    title: '装甲预言家',
    maxHp: 82,
    startingGold: 65,
    startingDeck: CONTROL_DECK,
    startingRelics: ['glacial_globe'],
    description: '以厚重防御和稳定控制推进战斗，承受伤害后寻找反击窗口。',
    color: '#a4a8ad',
    _design: { archetypes: ['防御', '控制', '慢速'] },
  },
  {
    id: 'storm_duelist',
    name: '岚刃决斗者',
    title: '风暴剑客',
    maxHp: 69,
    startingGold: 88,
    startingDeck: BURST_DECK,
    startingRelics: ['flux_core'],
    description: '依赖多段攻击与额外能量形成连续压制，但防线较薄。',
    color: '#6ec8ff',
    _design: { archetypes: ['快攻', '多段', '能量'] },
  },
  {
    id: 'night_alchemist',
    name: '夜色炼金师',
    title: '瓶中月影',
    maxHp: 64,
    startingGold: 105,
    startingDeck: CONTROL_DECK,
    startingRelics: ['treasure_compass'],
    description: '起始资源更充足，适合围绕奖励、商店和事件规划成长路线。',
    color: '#c58cff',
    _design: { archetypes: ['经济', '奖励', '规划'] },
  },
  {
    id: 'sunward_ranger',
    name: '逐日游侠',
    title: '光轨猎手',
    maxHp: 71,
    startingGold: 82,
    startingDeck: FLUX_DECK,
    startingRelics: ['frozen_amulet'],
    description: '在攻击和防守之间保持均衡，适合稳定推进地图路线。',
    color: '#ffd166',
    _design: { archetypes: ['均衡', '稳定', '路线'] },
  },
  {
    id: 'deepwarden',
    name: '深渊守望',
    title: '沉默盾卫',
    maxHp: 84,
    startingGold: 60,
    startingDeck: FROST_DECK,
    startingRelics: ['glacial_globe'],
    description: '高生命与强防御让他能承受更长战斗，适合耐心构筑。',
    color: '#2f6f8f',
    _design: { archetypes: ['高生命', '防御', '消耗'] },
  },
  {
    id: 'circuit_witch',
    name: '回路女巫',
    title: '电弧编织者',
    maxHp: 62,
    startingGold: 100,
    startingDeck: FLUX_DECK,
    startingRelics: ['spark_capacitor'],
    description: '擅长用技能和能量回路制造爆发回合，容错率较低。',
    color: '#f45bd2',
    _design: { archetypes: ['技能', '爆发', '能量'] },
  },
  {
    id: 'ash_nomad',
    name: '灰烬游民',
    title: '荒原旅者',
    maxHp: 74,
    startingGold: 75,
    startingDeck: BURST_DECK,
    startingRelics: ['frozen_amulet'],
    description: '兼具攻击和基础防御，适合测试新卡牌与新遗物组合。',
    color: '#b88a5a',
    _design: { archetypes: ['测试', '攻击', '防御'] },
  },
];

CHARACTERS.forEach(registerCharacter);
